### PR TITLE
Automatically rename Zulip topics for MCPs when the GitHub issue is renamed

### LINKED ISSUE #701: Link to Zulip stream from GitHub issue is broken
### Rustbot's link

https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Use.20sane.20defaults.20in.20x.py.20compiler-team.23326

### Actual link

https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Improve.20defaults.20in.20x.2Epy.20compiler-team.23326

### Diff

```diff
-https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Use.20sane.20defaults.20in.20x.py.20compiler-team.23326
+https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Improve.20defaults.20in.20x.2Epy.20compiler-team.23326
```

## Summary

I think there are two issues here:
1. Rustbot has `xxx` instead of `t-compiler.2Fmajor-changes`
2. The GitHub issue name was changed and Rustbot didn't update the link. I'm not sure if it's worth it, but maybe there's a way to listen for a title change and then update the link or at least post the new one?

Cc https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Improve.20defaults.20in.20x.2Epy.20compiler-team.23326/near/204243761

This issue has been assigned to @camelid via [this comment](https://github.com/rust-lang/triagebot/issues/701#issuecomment-660368589).

### PR DESCRIPTION
**Pull request by camelid**
Fixes #701

r? @Mark-Simulacrum

### CODE REVIEW

File: src/handlers/major_change.rs [hunk 1]
```diff
@@ -173,6 +178,41 @@ async fn handle_input(
...
+            let zulip_send_res = zulip_send_req
+                .send(&ctx.github.raw())
+                .await
+                .context("zulip post failed")?;
+
+            let zulip_send_res: crate::zulip::MessageApiResponse = zulip_send_res.json().await?;
+
+            let zulip_update_req = crate::zulip::UpdateMessageApiRequest {
+                message_id: zulip_send_res.message_id,
+                topic: Some("TODO"),
```
Comment (camelid) [inline src/handlers/major_change.rs:206]: Need to get the actual GitHub issue title.

File: src/handlers/major_change.rs [hunk 2]
```diff
@@ -173,6 +178,41 @@ async fn handle_input(
...
+                &issue.title[..std::cmp::min(issue.title.len(), 60 - zulip_topic.len())],
+            );
+
+            let zulip_send_req = crate::zulip::MessageApiRequest {
+                recipient: crate::zulip::Recipient::Stream {
+                    id: config.zulip_stream,
+                    topic: &zulip_topic,
+                },
+                content: "The associated GitHub issue has been renamed. Renaming this Zulip topic.",
+            };
```
Comment (camelid) [inline src/handlers/major_change.rs:196]: Hmm, I think this will post a new topic with the new title rather than posting to the old topic. I guess we'll have to include the old title in `Invocation::Rename`?

File: src/github.rs [hunk 3]
```diff
@@ -250,6 +250,38 @@ pub struct Issue {
...
+            } else {
+                format!("{}#{}", repo.repository, self.number)
+            }
+        } else {
+            format!("{}/{}#{}", repo.organization, repo.repository, self.number)
+        }
+    }
+}
+
+impl From<&Issue> for PartialIssue {
```
Comment (camelid) [inline src/github.rs:275]: This clones some of the fields. Is this the right trait for that? I couldn’t think of a better one

File: src/github.rs [hunk 4]
```diff
@@ -250,6 +250,38 @@ pub struct Issue {
...
+    fn from(other: &Issue) -> PartialIssue {
+        PartialIssue {
+            number: other.number,
+            title: other.title.clone(),
+            repository: other.repository.get().unwrap().clone(),
```
Comment (camelid) [inline src/github.rs:280]: Is it okay to unwrap the `OnceCell`?

**Comment by camelid** [comment]
CI doesn't seem to be working

**Comment by camelid** [comment]
Tried to fix it by closing and reopening it, but it didn't seem to work

**Comment by Mark-Simulacrum** [comment]
Hm maybe due to the merge conflict? Let's try resolving that.

**Comment by camelid** [comment]
Huh, I'm having trouble resolving the merge conflicts. It seems that `src/handlers/major_change.rs` was majorly refactored?

**Comment by camelid** [comment]
It looks like there's some rebase advice [here](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/rebasing.20help.20after.20the.20move.20to.20.60library.2F.60/near/205279826)

I think I might try that (making a new branch and cherry-picking)

**Comment by kellda** [comment]
@camelid I rebased your work onto master, it's available at https://github.com/kellda/triagebot/tree/auto-mcp-rename
(btw I'm likely the one who majorly refactored `src/handlers/*`)

**Comment by camelid** [comment]
Wow, thank you! It's been so long since I worked on this that I can't remember the details, but let me see if I can pick up where I left off.

**Comment by camelid** [comment]
It looks to me like this might be close. @Mark-Simulacrum could you re-review then when you get a chance?

File: src/interactions.rs [hunk 5]
```diff
@@ -1,31 +1,50 @@
...
+        Comment {
+            issue,
+            message: message.into(),
+        }
+    }
+
+    pub async fn post(&self, client: &GithubClient) -> anyhow::Result<()> {
+        self.issue.post_comment(client, &self.message).await
+    }
+}
```
Comment (Mark-Simulacrum) [inline src/interactions.rs:23]: There's no need for a separate Comment struct, we can directly call post_comment. ErrorComment exists because it does more than that.

File: src/handlers/major_change.rs [hunk 6]
```diff
@@ -207,3 +241,21 @@ async fn handle(
     gh_res.context("label setting failed")?;
     Ok(())
 }
+
+fn zulip_topic_from_issue(issue: &PartialIssue) -> String {
```
Comment (Mark-Simulacrum) [inline src/handlers/major_change.rs:245]: I would prefer to rename the PartialIssue struct and call it something like "ZulipGitHubReference" or something like that -- I don't think we want to be converting it directly from Issue, rather we should be manually constructing it when needed in code. I think the into() is only called once anyway.

File: src/handlers/major_change.rs [hunk 7]
```diff
@@ -85,6 +99,39 @@ pub(super) async fn handle_input(
...
+                .send(&ctx.github.raw())
+                .await
+                .context("zulip post failed")?;
+
+            let zulip_send_res: crate::zulip::MessageApiResponse = zulip_send_res.json().await?;
+
+            let zulip_update_req = crate::zulip::UpdateMessageApiRequest {
+                message_id: zulip_send_res.message_id,
+                topic: Some(&new_topic),
+                ..Default::default()
```
Comment (Mark-Simulacrum) [inline src/handlers/major_change.rs:126]: Please avoid Default impls on API structs, I'd prefer to either not include the unnecessary fields or to explicitly list them here.

File: src/handlers/major_change.rs [hunk 8]
```diff
@@ -85,6 +99,39 @@ pub(super) async fn handle_input(
...
+                recipient: crate::zulip::Recipient::Stream {
+                    id: config.zulip_stream,
+                    topic: &prev_topic,
+                },
+                content: "The associated GitHub issue has been renamed. Renaming this Zulip topic.",
+            };
+            let zulip_send_res = zulip_send_req
+                .send(&ctx.github.raw())
+                .await
+                .context("zulip post failed")?;
```
Comment (Mark-Simulacrum) [inline src/handlers/major_change.rs:119]: Why are we sending a separate message for this? Can we not just rename the topic? It seems like either way I would want to post the message *after* we attempt to rename the topic.

Comment (camelid) [reply src/handlers/major_change.rs:119]: I think we discussed this a few months ago, but I think the way you rename a topic in Zulip is to send an UpdateMessage request, but we need a message in the topic to update it, so it sends a new message to the old topic and then updates the new message to use the new topic.

Comment (Mark-Simulacrum) [reply src/handlers/major_change.rs:119]: Ok. Seems fine.

File: src/interactions.rs (hunk 5 above)
Comment (camelid) [reply src/interactions.rs]: It turns out that `Comment` struct wasn't even being used.... I must have added it for something that I didn't up needing.

File: src/handlers/major_change.rs (hunk 6 above)
Comment (camelid) [reply src/handlers/major_change.rs]: I renamed, but I think we should keep the `From` impl. It is in fact used twice, and I'd rather have the code in one place. That said, if you would still prefer to inline the From impl and get rid of it, I am still open to it.

Comment (Mark-Simulacrum) [reply src/handlers/major_change.rs]: I think it's fine as a function or so, I just don't particularly like From/Into impls being used in non-generic code.

Comment (camelid) [reply src/handlers/major_change.rs]: Okay, I converted it to a method on `Issue`. I think I agree that it's better this way :)

**Comment by camelid** [comment]
At long last! 🎉 

I think this was one of my longest-open PRs. Thanks for reviewing it and thanks to kellda for rebasing it for me!
